#!/usr/bin/env python3
"""
Helper script to add new test data with ground truth generation.

Usage:
    python add_test_data.py path/to/document.pdf
    python add_test_data.py path/to/receipt.jpg --type receipt
"""

import argparse
import json
import shutil
from pathlib import Path

from modal_client import ModalClient

# Modal endpoints
ENDPOINT_7B = "https://ben-ebsworth--pfinance-extraction-7b-web-app.modal.run"
ENDPOINT_2B = "https://ben-ebsworth--pfinance-extraction-cheap-web-app.modal.run"

TESTDATA_DIR = Path(__file__).parent.parent / "web" / "testdata"


def main():
    parser = argparse.ArgumentParser(description="Add new test data with ground truth")
    parser.add_argument("file", help="Document file to add")
    parser.add_argument("--type", choices=["receipt", "bank_statement", "auto"],
                       default="auto", help="Document type")
    parser.add_argument("--model", choices=["7B", "2B"], default="7B",
                       help="Model to use for initial extraction")
    parser.add_argument("--no-copy", action="store_true",
                       help="Don't copy file to testdata directory")
    parser.add_argument("--verify", action="store_true",
                       help="Interactive verification of extracted data")

    args = parser.parse_args()

    source_path = Path(args.file)
    if not source_path.exists():
        print(f"Error: File not found: {source_path}")
        return 1

    # Determine destination
    if args.no_copy:
        dest_path = source_path
    else:
        dest_path = TESTDATA_DIR / source_path.name
        if dest_path.exists():
            response = input(f"{dest_path.name} already exists. Overwrite? [y/N] ")
            if response.lower() != 'y':
                print("Aborted.")
                return 1

    # Select endpoint
    endpoint = ENDPOINT_7B if args.model == "7B" else ENDPOINT_2B
    print(f"Using {args.model} model at {endpoint}")

    # Extract
    print(f"Extracting from: {source_path.name}")
    client = ModalClient(endpoint=endpoint)

    try:
        result = client.extract(source_path, args.type)
    except Exception as e:
        print(f"Extraction failed: {e}")
        return 1

    print(f"Extracted {len(result.transactions)} transactions")

    # Copy file if needed
    if not args.no_copy and source_path != dest_path:
        shutil.copy(source_path, dest_path)
        print(f"Copied to: {dest_path}")

    # Create ground truth
    gt_path = dest_path.with_suffix(".gt.json")

    doc_type = result.doc_type
    if doc_type == "auto":
        doc_type = "bank_statement" if dest_path.suffix.lower() == ".pdf" else "receipt"

    ground_truth = {
        "document_type": doc_type,
        "notes": f"Generated by {args.model} model - please review and correct",
        "transactions": result.transactions,
    }

    # Interactive verification
    if args.verify and result.transactions:
        print("\n" + "="*60)
        print("VERIFICATION (press Enter to accept, or type correction)")
        print("="*60)

        verified_transactions = []
        for i, t in enumerate(result.transactions):
            print(f"\n[{i+1}/{len(result.transactions)}]")
            print(f"  Date: {t.get('date', 'N/A')}")
            print(f"  Description: {t.get('description', t.get('merchant', 'N/A'))}")
            print(f"  Amount: {t.get('amount', t.get('total', 'N/A'))}")

            response = input("  Accept? [Y/n/edit] ").strip().lower()

            if response == 'n':
                print("  Skipped.")
                continue
            elif response == 'edit':
                date = input(f"  Date [{t.get('date', '')}]: ").strip()
                desc = input(f"  Description [{t.get('description', t.get('merchant', ''))}]: ").strip()
                amt = input(f"  Amount [{t.get('amount', t.get('total', ''))}]: ").strip()

                if date:
                    t['date'] = date
                if desc:
                    if 'description' in t:
                        t['description'] = desc
                    else:
                        t['merchant'] = desc
                if amt:
                    try:
                        if 'amount' in t:
                            t['amount'] = float(amt)
                        else:
                            t['total'] = float(amt)
                    except ValueError:
                        pass

            verified_transactions.append(t)

        ground_truth["transactions"] = verified_transactions
        ground_truth["notes"] = f"Verified from {args.model} model extraction"

    # Save ground truth
    with open(gt_path, 'w') as f:
        json.dump(ground_truth, f, indent=2)

    print(f"\nGround truth saved to: {gt_path}")
    print(f"Transactions: {len(ground_truth['transactions'])}")

    if not args.verify:
        print("\nNote: Please review and correct the ground truth file manually.")
        print(f"      Edit: {gt_path}")

    return 0


if __name__ == "__main__":
    exit(main())
